# Generated by Django 2.1.15 on 2020-01-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
